"""empty message

Revision ID: 733435842c25
Revises: f99a5b7ef910
Create Date: 2019-02-19 14:21:45.194037

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '733435842c25'
down_revision = 'f99a5b7ef910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=False),
        sa.Column('start_date', sqlalchemy_utils.types.arrow.ArrowType(), server_default=func.now(), nullable=True),
        sa.Column('end_date', sqlalchemy_utils.types.arrow.ArrowType(), server_default=func.now(), nullable=True),
        sa.Column('type', sa.String(length=255), nullable=True),
        sa.Column('workers_needed', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('description'),
        sa.UniqueConstraint('location'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_services_end_date'), 'services', ['end_date'], unique=False)
    op.create_index(op.f('ix_services_start_date'), 'services', ['start_date'], unique=False)

    op.create_table('client_services',
        sa.Column('service_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('service_id', 'user_id')
    )

    op.create_table('worker_services',
        sa.Column('service_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('service_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_services')
    op.drop_table('client_services')
    op.drop_index(op.f('ix_services_start_date'), table_name='services')
    op.drop_index(op.f('ix_services_end_date'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
