"""empty message

Revision ID: 810840519f99
Revises: 733435842c25
Create Date: 2019-02-20 13:45:59.926402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810840519f99'
down_revision = '733435842c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description', table_name='services')
    op.drop_index('location', table_name='services')
    op.drop_index('name', table_name='services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'services', ['name'], unique=True)
    op.create_index('location', 'services', ['location'], unique=True)
    op.create_index('description', 'services', ['description'], unique=True)
    # ### end Alembic commands ###
