"""empty message

Revision ID: f99a5b7ef910
Revises: c87ca08982be
Create Date: 2019-02-19 14:01:10.344115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f99a5b7ef910'
down_revision = 'c87ca08982be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.UnicodeText(), nullable=False))
    op.drop_column('users', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title', mysql.TEXT(), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
